export const QUERIES_KEY = {
  CATEGORY: {
    GET_CATEGORIES: 'GET_CATEGORIES'
  },
  PRODUCT: {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    GET_PRODUCT_VARIANTS: 'GET_PRODUCT_VARIANTS'
  },
  AUTH: {
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD'
  },
  CART: {
    GET_CART: 'GET_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART'
  }
};
