export const QUERIES_KEY = {
  CATEGORY: {
    GET_CATEGORIES: 'GET_CATEGORIES'
  },
  PRODUCT: {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    GET_PRODUCT_VARIANTS: 'GET_PRODUCT_VARIANTS'
  }
};
